-- this file is automatically generated
setParam("fullscreen", "1")
setParam("lang", "fr")
setParam("playtime", "492503")
setParam("show_steps", "0")
setParam("speech", "en")
setParam("subtitles", "1")
setParam("volume_music", "0")
setParam("volume_sound", "81")
